import { useMemo, useState } from "react";
import { AlertTriangle, ExternalLink, Loader2, MapPinned, Send, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { AIChatBox, type Message } from "@/components/AIChatBox";

export default function AIAssistantPage() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [domain, setDomain] = useState<"network" | "cx" | "sales" | "general">("network");
  const [selectedSites, setSelectedSites] = useState<string[]>([]);
  const ask = trpc.ai.ask.useMutation({ onSuccess: result => { setMessages(current => [...current, { role: "assistant", content: result.answer }]); setSelectedSites(result.relatedSiteIds ?? []); }, onError: error => setMessages(current => [...current, { role: "assistant", content: `I could not complete the analysis. ${error.message}` }]) });
  const prompts = useMemo(() => ["Why is Amman West critical?", "Show me congested sites with fiber availability.", "Which areas have complaints + churn + congestion?", "If I can fix only 5 things today, what should I fix?"], []);
  const send = (question: string) => { setMessages(current => [...current, { role: "user", content: question }]); ask.mutate({ question, domain }); };
  return <main className="standalone-module ai-control-room"><header className="module-page-hero"><div><div className="module-kicker"><span className="live-dot"/> DECISION COPILOT</div><h1>AI Assistant</h1><p>Ask natural-language questions. Smart Analytics grounds answers in operational signals and points you to affected locations.</p></div><div className="module-hero-icon"><Sparkles size={32}/></div></header><section className="ai-command-bar"><div className="ai-domain"><span>INTELLIGENCE DOMAIN</span><select value={domain} onChange={event => setDomain(event.target.value as typeof domain)}><option value="network">Network</option><option value="cx">Customer Experience</option><option value="sales">Sales</option><option value="general">General</option></select></div><div className="ai-scope"><Sparkles size={14}/> Answers are permission-scoped and data-grounded</div></section><section className="ai-layout"><div className="ai-chat-panel"><AIChatBox messages={messages} onSendMessage={send} isLoading={ask.isPending} height="610px" emptyStateMessage="Ask the decision copilot about your network, customers or business impact." suggestedPrompts={prompts}/></div><aside className="ai-context-panel"><div className="panel-eyebrow">MAP ACTION</div><h2>Related locations</h2>{selectedSites.length ? <><p>The last answer identified these sites. Open the map to continue the investigation.</p>{selectedSites.map(site => <div className="ai-site-chip" key={site}><MapPinned size={14}/><b>{site}</b><button onClick={() => { window.location.href = `/intelligence-map?site=${encodeURIComponent(site)}`; }}><ExternalLink size={13}/> Open map</button></div>)}</> : <div className="ai-empty"><AlertTriangle size={18}/><span>Ask about a site or operational pattern to receive map-linked context.</span></div>}{ask.isPending && <div className="ai-working"><Loader2 className="spin" size={14}/> Analyzing live operational context…</div>}</aside></section></main>;
}
export { AIAssistantPage };
