import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ExternalLink, Loader2, RefreshCw, UserRound } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Alert = { id: string; title: string; severity: "critical" | "high" | "warning" | "opportunity"; category: string; region: string; siteId: string; value: string; description: string; action: string; status: "open" | "acknowledged" | "resolved"; assignee: string | null };
export default function AlertsPage() {
  const { data, isLoading, refetch } = trpc.alerts.operations.useQuery() as { data?: Alert[]; isLoading: boolean; refetch: () => void };
  const updateStatus = trpc.alerts.updateStatus.useMutation();
  const [severity, setSeverity] = useState("all"); const [status, setStatus] = useState("open"); const [actionError, setActionError] = useState(""); const [local, setLocal] = useState<Record<string, Partial<Alert>>>({});
  const alerts = useMemo(() => (data ?? []).map(item => ({ ...item, ...local[item.id] })).filter(item => (severity === "all" || item.severity === severity) && (status === "all" || item.status === status)), [data, local, severity, status]);
  const update = (item: Alert, next: "acknowledged" | "resolved") => { const previous = local[item.id]; setActionError(""); setLocal(current => ({ ...current, [item.id]: { status: next, assignee: next === "acknowledged" ? "Operations queue" : item.assignee } })); updateStatus.mutate({ id: item.id, status: next, assignee: next === "acknowledged" ? "Operations queue" : undefined }, { onError: error => { setLocal(current => ({ ...current, [item.id]: previous ?? {} })); setActionError(error.message || "Unable to update alert status."); }, onSuccess: result => setLocal(current => ({ ...current, [item.id]: { status: result.status, assignee: result.assignee } })) }); };
  if (isLoading) return <main className="standalone-module"><div className="module-loading"><Loader2 className="spin" size={20}/> Loading operational alerts…</div></main>;
  return <main className="standalone-module alerts-page"><header className="module-page-hero"><div><div className="module-kicker"><span className="live-dot"/> ACTIVE SIGNALS</div><h1>Alerts</h1><p>Review operational signals, assign ownership, acknowledge risk and open the related location.</p></div><div className="module-hero-icon"><AlertTriangle size={32}/></div></header><section className="alerts-toolbar"><div><b>{alerts.length}</b><span>visible alerts</span></div><select value={severity} onChange={event => setSeverity(event.target.value)}><option value="all">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="warning">Warning</option><option value="opportunity">Opportunity</option></select><select value={status} onChange={event => setStatus(event.target.value)}><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option><option value="all">All statuses</option></select><button onClick={() => refetch()}><RefreshCw size={14}/> Refresh</button></section>{actionError && <div className="module-error compact"><AlertTriangle size={15}/>{actionError}</div>}<section className="alert-list">{alerts.map(item => <article className={`alert-card ${item.severity}`} key={item.id}><div className="alert-marker"><AlertTriangle size={17}/></div><div className="alert-copy"><div className="alert-topline"><b>{item.title}</b><span>{item.severity}</span></div><p>{item.description}</p><small>{item.region} · {item.value} · Recommended: {item.action}</small></div><div className="alert-actions"><button onClick={() => { window.location.href = `/intelligence-map?site=${encodeURIComponent(item.siteId)}`; }}><ExternalLink size={13}/> Open location</button>{item.status === "open" && <><button disabled={updateStatus.isPending} onClick={() => update(item, "acknowledged")}><UserRound size={13}/> Acknowledge</button><button disabled={updateStatus.isPending} onClick={() => update(item, "resolved")}><CheckCircle2 size={13}/> Resolve</button></>}{item.status !== "open" && <em>{item.status}</em>}</div></article>)}{!alerts.length && <div className="module-state">No alerts match the selected filters.</div>}</section></main>;
}
export { AlertsPage };
