import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ExternalLink, Loader2, RefreshCw, Search, UserRound } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Alert = { id: string; title: string; severity: "critical" | "high" | "warning" | "opportunity"; category: string; region: string; siteId: string; value: string; description: string; action: string; status: "open" | "acknowledged" | "resolved"; assignee: string | null; createdAt: string; updatedAt?: string };
function age(value: string) { const time = Date.parse(value); if (!Number.isFinite(time)) return "time unavailable"; const minutes = Math.max(0, Math.round((Date.now() - time) / 60000)); return minutes < 60 ? `${minutes}m old` : `${Math.round(minutes / 60)}h old`; }
export default function AlertsPage() {
  const { data, isLoading, refetch } = trpc.alerts.operations.useQuery() as { data?: Alert[]; isLoading: boolean; refetch: () => void };
  const updateStatus = trpc.alerts.updateStatus.useMutation();
  const [severity, setSeverity] = useState("all"); const [category, setCategory] = useState("all"); const [status, setStatus] = useState("open"); const [search, setSearch] = useState(""); const [actionError, setActionError] = useState(""); const [local, setLocal] = useState<Record<string, Partial<Alert>>>({});
  const alerts = useMemo(() => { const q = search.trim().toLowerCase(); return (data ?? []).map(item => ({ ...item, ...local[item.id] })).filter(item => (severity === "all" || item.severity === severity) && (category === "all" || item.category === category) && (status === "all" || item.status === status) && (!q || `${item.title} ${item.region} ${item.siteId} ${item.description}`.toLowerCase().includes(q))); }, [data, local, severity, category, status, search]);
  const update = (item: Alert, next: "acknowledged" | "resolved") => { const previous = local[item.id]; setActionError(""); setLocal(current => ({ ...current, [item.id]: { status: next, assignee: next === "acknowledged" ? "Operations queue" : item.assignee } })); updateStatus.mutate({ id: item.id, status: next, assignee: next === "acknowledged" ? "Operations queue" : undefined }, { onError: error => { setLocal(current => ({ ...current, [item.id]: previous ?? {} })); setActionError(error.message || "Unable to update alert status."); }, onSuccess: result => setLocal(current => ({ ...current, [item.id]: { status: result.status, assignee: result.assignee, updatedAt: result.updatedAt } })) }); };
  if (isLoading) return <main className="standalone-module"><div className="module-loading"><Loader2 className="spin" size={20}/> Loading operational alerts…</div></main>;
  return <main className="standalone-module alerts-page"><header className="module-page-hero"><div><div className="module-kicker"><span className="live-dot"/> OPERATIONAL SIGNALS</div><h1>Alerts</h1><p>Review operational signals, assign ownership, acknowledge risk and open the related location.</p></div><div className="module-hero-icon"><AlertTriangle size={32}/></div></header><section className="alerts-toolbar"><div><b>{alerts.length}</b><span>filtered results</span></div><label className="alerts-search"><Search size={14}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search site, region or alert" /></label><select value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option><option value="network">Network</option><option value="customer">Customer</option><option value="revenue">Revenue</option><option value="fiber">Fiber</option><option value="opportunity">Opportunity</option></select><select value={severity} onChange={event => setSeverity(event.target.value)}><option value="all">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="warning">Warning</option><option value="opportunity">Opportunity</option></select><select value={status} onChange={event => setStatus(event.target.value)}><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option><option value="all">All statuses</option></select><button onClick={() => refetch()}><RefreshCw size={14}/> Refresh</button></section>{actionError && <div className="module-error compact"><AlertTriangle size={15}/>{actionError}</div>}<section className="alert-list">{alerts.map(item => <article className={`alert-card ${item.severity}`} key={item.id}><div className="alert-marker"><AlertTriangle size={17}/></div><div className="alert-copy"><div className="alert-topline"><b>{item.title}</b><span>{item.severity}</span></div><p>{item.description}</p><small>{item.region} · {item.siteId} · {item.value} · {age(item.createdAt)} · Recommended: {item.action}</small></div><div className="alert-actions"><button onClick={() => { window.location.href = `/intelligence-map?site=${encodeURIComponent(item.siteId)}`; }}><ExternalLink size={13}/> Open location</button>{item.status === "open" && <><button disabled={updateStatus.isPending} onClick={() => update(item, "acknowledged")}><UserRound size={13}/> Acknowledge</button><button disabled={updateStatus.isPending} onClick={() => update(item, "resolved")}><CheckCircle2 size={13}/> Resolve</button></>}{item.status !== "open" && <em>{item.status}{item.assignee ? ` · ${item.assignee}` : ""}</em>}</div></article>)}{!alerts.length && <div className="module-state">No alerts match the selected filters.</div>}</section></main>;
}
export { AlertsPage };
