import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, Building2, CheckCircle2, CircleDollarSign, Gauge, Loader2, MapPinned, RefreshCw, ShieldAlert, TrendingUp, Users, Wifi } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Area = { id: string; region: string; period: string; revenueAtRisk: number; customersAtRisk: number; enterpriseImpact: number; salesPipeline: number; revenueOpportunity: number | null; investmentOpportunity: number | null; networkHealth: number | null; networkIssue: boolean | null; action: string; status: string; riskShare: number };
type Operations = { source: "persisted"; updatedAt: string; summary: { revenueAtRisk: number; customersAtRisk: number; enterpriseImpact: number; salesPipeline: number; revenueOpportunity: number | null; investmentOpportunity: number | null; areasAtRisk: number }; areas: Area[] };
const jod = (value: number | null) => value === null ? "—" : value >= 1000000 ? `${(value / 1000000).toFixed(2)}M JOD` : `${Math.round(value / 1000)}K JOD`;

export default function BusinessRevenuePage() {
  const { data, isLoading, isError, refetch } = trpc.businessRevenue.operations.useQuery() as { data?: Operations; isLoading: boolean; isError: boolean; refetch: () => void };
  const [riskOnly, setRiskOnly] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => (data?.areas ?? []).filter(item => !riskOnly || item.networkIssue), [data?.areas, riskOnly]);
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0];
  if (isLoading) return <main className="standalone-module revenue-page"><div className="module-loading"><Loader2 className="animate-spin" size={22}/><span>Loading business intelligence…</span></div></main>;
  if (isError || !data) return <main className="standalone-module revenue-page"><div className="module-error"><AlertTriangle size={22}/><h2>Business data unavailable</h2><p>Could not load revenue exposure and opportunity intelligence. Check the source connection and retry.</p><button onClick={() => refetch()}><RefreshCw size={14}/> Retry</button></div></main>;
  const s = data.summary;
  return <main className="standalone-module revenue-page">
    <header className="module-page-hero revenue-hero"><div><div className="module-kicker"><span className="live-dot"/> REVENUE COMMAND</div><h1>Business &amp; Revenue</h1><p>Translate technical exposure into financial decisions, investment priorities and commercial upside.</p></div><div className="revenue-hero-icon"><CircleDollarSign size={34}/><span/></div></header>
    <div className="revenue-source"><span><TrendingUp size={13}/> Persisted revenue dataset</span><small>Source period · Updated {new Date(data.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</small><small>{s.areasAtRisk} areas require investment review</small></div>
    <section className="revenue-summary-grid"><Metric icon={CircleDollarSign} label="Revenue at risk / month" value={jod(s.revenueAtRisk)} hint="Network-linked exposure" tone="risk" /><Metric icon={Users} label="Customers at risk" value={s.customersAtRisk.toLocaleString()} hint="Retention exposure" tone="accent" /><Metric icon={Building2} label="Enterprise impact" value={s.enterpriseImpact.toLocaleString()} hint="Accounts requiring care" /><Metric icon={TrendingUp} label="Sales pipeline" value={jod(s.salesPipeline)} hint="Commercial upside" tone="good" /><Metric icon={ArrowUpRight} label="Revenue opportunity" value={jod(s.revenueOpportunity)} hint="Identified upside" tone="good" /><Metric icon={ShieldAlert} label="Investment opportunity" value={jod(s.investmentOpportunity)} hint="Prioritised action value" tone="accent" /></section>
    <section className="revenue-filter"><div><p className="panel-eyebrow">BUSINESS EXPOSURE</p><h2>Regional financial sensitivity</h2></div><label className={`revenue-toggle ${riskOnly ? "active" : ""}`}><input type="checkbox" checked={riskOnly} onChange={event => setRiskOnly(event.target.checked)}/><span/> Network risk areas only</label></section>
    <section className="revenue-main-grid"><div className="revenue-area-panel"><div className="panel-heading"><div><p className="panel-eyebrow">REGIONAL IMPACT</p><h2>Revenue risk by area</h2><span>Monthly exposure, customers and recommended action</span></div><MapPinned size={20}/></div><div className="revenue-area-list">{filtered.map((item, index) => <button className={`revenue-area-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelectedId(item.id)}><span className={`revenue-index ${item.networkIssue ? "risk" : ""}`}>{String(index + 1).padStart(2, "0")}</span><span className="revenue-area-name"><b>{item.region}</b><small>{item.status} · {item.action}</small></span><span className="revenue-risk-value"><b>{jod(item.revenueAtRisk)}</b><small>{item.riskShare}% of exposure</small></span><span className="revenue-area-health"><i><em style={{ width: `${item.networkHealth ?? 0}%` }}/></i><small>Network health {item.networkHealth === null ? "—" : `${Math.round(item.networkHealth)}%`}</small></span><span className={`revenue-status ${item.networkIssue === true ? "risk" : item.networkIssue === false ? "good" : "neutral"}`}>{item.networkIssue === true ? <AlertTriangle size={15}/> : <CheckCircle2 size={15}/>}</span></button>)}{!filtered.length && <div className="revenue-empty">No regions match this filter.</div>}</div></div><div className="revenue-opportunity-panel"><div className="panel-heading"><div><p className="panel-eyebrow">CAPITAL ALLOCATION</p><h2>Opportunity view</h2></div><Gauge size={20}/></div><div className="revenue-opportunity-list"><Opportunity label="Revenue upside" value={jod(s.revenueOpportunity)} tone="good"/><Opportunity label="Investment case" value={jod(s.investmentOpportunity)} tone="accent"/><Opportunity label="Pipeline sensitivity" value={jod(s.salesPipeline)} tone="accent"/><div className="revenue-investment-note"><ShieldAlert size={16}/><span><b>Decision lens</b><small>Prioritise remediation where revenue exposure and network risk overlap.</small></span></div></div></div></section>
    {selected && <section className={`revenue-detail ${selected.networkIssue ? "at-risk" : ""}`}><div className="revenue-detail-heading"><div><p className="panel-eyebrow">SELECTED REGION</p><h2>{selected.region}</h2><p>{selected.period} · {selected.status} · {selected.action}</p></div><div className="revenue-detail-value"><small>MONTHLY REVENUE AT RISK</small><b>{jod(selected.revenueAtRisk)}</b><span>{selected.riskShare}% of total exposure</span></div></div><div className="revenue-detail-grid"><Detail label="Customers at risk" value={selected.customersAtRisk.toLocaleString()} icon={Users} tone="accent"/><Detail label="Enterprise impact" value={selected.enterpriseImpact.toLocaleString()} icon={Building2}/><Detail label="Sales pipeline" value={jod(selected.salesPipeline)} icon={TrendingUp} tone="good"/><Detail label="Revenue opportunity" value={jod(selected.revenueOpportunity)} icon={ArrowUpRight} tone="good"/><Detail label="Network health" value={selected.networkHealth === null ? "—" : `${Math.round(selected.networkHealth)}%`} icon={Wifi} tone={selected.networkIssue === true ? "risk" : "good"}/></div><div className={`revenue-callout ${selected.networkIssue === true ? "risk" : "good"}`}>{selected.networkIssue === true ? <AlertTriangle size={18}/> : <CheckCircle2 size={18}/>}<span><b>{selected.networkIssue === true ? "Investment priority" : selected.networkIssue === null ? "Network linkage unavailable" : "Commercial opportunity"}</b><small>{selected.networkIssue === true ? `${selected.action} recommended to protect ${jod(selected.revenueAtRisk)} monthly exposure and preserve ${selected.customersAtRisk.toLocaleString()} customers.` : selected.networkIssue === null ? "Connect network KPI data to calculate the technical linkage for this revenue record." : `The source does not provide a revenue opportunity value for this area.`}</small></span></div></section>}
  </main>;
}
function Metric({ icon: Icon, label, value, hint, tone = "" }: { icon: typeof CircleDollarSign; label: string; value: string; hint: string; tone?: string }) { return <div className="revenue-metric"><span><Icon size={16}/></span><small>{label}</small><strong className={tone}>{value}</strong><em>{hint}</em></div>; }
function Opportunity({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="revenue-opportunity"><span><b>{label}</b><small>Across selected regions</small></span><strong className={tone}>{value}</strong></div>; }
function Detail({ icon: Icon, label, value, tone = "" }: { icon: typeof Gauge; label: string; value: string; tone?: string }) { return <div className="revenue-detail-metric"><Icon size={15}/><span>{label}</span><b className={tone}>{value}</b></div>; }
export { BusinessRevenuePage };
