import { useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, AlertTriangle, BarChart3, CheckCircle2, CircleDot, Filter, Loader2, MapPin, Network, Search, ShieldCheck, TrendingUp, Users } from "lucide-react";
import { useLocation } from "wouter";
import { MapView } from "@/components/Map";
import { trpc } from "@/lib/trpc";

type Severity = "all" | "low" | "medium" | "high" | "critical";
type Hotspot = { id: string; region: string; complaints: number; openComplaints: number; networkRelated: number; networkShare: number; coveredWorstCellCount: number; coveredShare: number; criticalComplaints: number; latitude: number | null; longitude: number | null; worstCells: string[]; severity: "low" | "medium" | "high" | "critical"; categories: string[] };
type Category = { category: string; count: number; networkRelated: number; growthPct: number; severity: "low" | "medium" | "high" | "critical" };
type Operations = { source: "persisted"; updatedAt: string; summary: { totalComplaints: number; openComplaints: number; networkRelated: number; networkShare: number; complaintGrowthPct: number; hotspots: number; criticalComplaints: number; worstCellCoverageShare: number; worstCellsInCoverage: number }; categories: Category[]; severities: Array<{ severity: "low" | "medium" | "high" | "critical"; count: number }>; hotspots: Hotspot[]; trends: Array<{ label: string; count: number }> };

function fmt(value: number) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value); }
function compact(value: number) { return value >= 1000 ? `${(value / 1000).toFixed(value >= 10000 ? 0 : 1)}K` : fmt(value); }
function dateTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Unknown" : date.toLocaleString([], { dateStyle: "medium", timeStyle: "short" }); }
function pointPosition(point: { latitude: number; longitude: number }) { return { left: `${Math.max(8, Math.min(92, ((point.longitude - 34.85) / 1.45) * 100))}%`, top: `${Math.max(10, Math.min(90, ((33.2 - point.latitude) / 3.9) * 100))}%` }; }
function located(point: Hotspot): point is Hotspot & { latitude: number; longitude: number } { return point.latitude !== null && point.longitude !== null; }

export default function ComplaintsPage() {
  const [, navigate] = useLocation();
  const permissions = trpc.auth.permissions.useQuery();
  const query = trpc.complaints.operations.useQuery(undefined, { enabled: Boolean(permissions.data?.grants?.includes("complaints.view")) });
  const data = query.data as Operations | undefined;
  const [category, setCategory] = useState("all");
  const [severity, setSeverity] = useState<Severity>("all");
  const [region, setRegion] = useState("all");
  const [networkOnly, setNetworkOnly] = useState(false);
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const mapRef = useRef<google.maps.Map | null>(null);
  const [mapReady, setMapReady] = useState(false);
  const overlaysRef = useRef<Array<{ setMap: (map: google.maps.Map | null) => void }>>([]);
  const regions = useMemo(() => Array.from(new Set((data?.hotspots ?? []).map(item => item.region))), [data?.hotspots]);
  const categories = useMemo(() => data?.categories ?? [], [data?.categories]);
  const visibleHotspots = useMemo(() => { const q = search.trim().toLowerCase(); return (data?.hotspots ?? []).filter(item => (!region || region === "all" || item.region === region) && (severity === "all" || item.severity === severity) && (category === "all" || item.categories.includes(category)) && (!networkOnly || item.networkRelated > 0) && (!q || item.region.toLowerCase().includes(q))); }, [data?.hotspots, category, severity, region, networkOnly, search]);
  const selected = visibleHotspots.find(item => item.id === selectedId) ?? visibleHotspots[0] ?? data?.hotspots[0];
  const mapCenter = selected && located(selected) ? { lat: selected.latitude, lng: selected.longitude } : { lat: 0, lng: 0 };

  useEffect(() => {
    if (!mapRef.current || !window.google?.maps?.marker || !visibleHotspots.length) return;
    overlaysRef.current.forEach(item => item.setMap(null));
    const overlays: Array<{ setMap: (map: google.maps.Map | null) => void }> = [];
    visibleHotspots.filter(located).forEach(hotspot => {
      const pin = document.createElement("div"); pin.className = `complaint-map-pin ${hotspot.coveredShare >= 70 ? "network" : ""}`; pin.textContent = "!"; pin.title = `${hotspot.region}: ${fmt(hotspot.complaints)} complaints`;
      const marker = new google.maps.marker.AdvancedMarkerElement({ map: mapRef.current, position: { lat: hotspot.latitude, lng: hotspot.longitude }, title: pin.title, content: pin }); marker.addListener("click", () => setSelectedId(hotspot.id)); overlays.push(marker as unknown as { setMap: (map: google.maps.Map | null) => void });
    });
    overlaysRef.current = overlays;
    return () => overlays.forEach(item => item.setMap(null));
  }, [visibleHotspots, mapReady]);

  if (permissions.isLoading) return <div className="auth-loading"><Loader2 size={18} className="spin" /> Loading protected complaints workspace…</div>;
  if (!permissions.data?.grants?.includes("complaints.view")) return <main className="module-access-denied"><ShieldCheck size={28} /><h1>Access restricted</h1><p>Your role does not have permission to view complaint intelligence.</p><button onClick={() => navigate("/")}>Return to command center</button></main>;
  if (query.isLoading) return <div className="auth-loading"><Loader2 size={18} className="spin" /> Loading complaint intelligence…</div>;
  if (query.isError || !data) return <main className="module-access-denied"><CircleDot size={28} /><h1>Complaint data unavailable</h1><p>We could not load the complaint dataset. Check the connected source and retry.</p><button onClick={() => query.refetch()}>Retry complaint data</button></main>;

  const maxTrend = Math.max(...data.trends.map(item => item.count), 1);
  return <main className="standalone-module complaints-operations-page">
    <header className="standalone-top"><button onClick={() => navigate("/")}>← Command Center</button><span className="section-kicker">VOICE OF CUSTOMER</span><span className="module-role"><ShieldCheck size={14} /> Role-scoped view</span></header>
    <section className="standalone-hero complaints-page-hero"><div><span className="section-kicker">COMPLAINTS</span><h1>Turn complaint pressure into network action.</h1><p>Connect category, severity and growth to the network locations where customers are feeling the service impact.</p></div><div className="standalone-icon"><AlertTriangle size={28} /></div></section>
    <section className="complaints-source-strip"><div><span className="network-live-dot" /><b>Persisted complaint intelligence</b><span>Updated {dateTime(data.updatedAt)}</span></div><span>{data.summary.hotspots} hotspots monitored</span></section>
    <section className="complaints-summary-grid"><div className="complaints-total-card"><span>Total Complaints</span><strong>{fmt(data.summary.totalComplaints)}</strong><small><AlertTriangle size={14} /> all recorded cases</small></div><div className="complaints-metric-card"><span>Open Complaints</span><strong>{fmt(data.summary.openComplaints)}</strong><small className="risk"><CircleDot size={14} /> active queue</small></div><div className="complaints-metric-card"><span>Network-related</span><strong>{data.summary.networkShare.toFixed(1)}%</strong><small><Network size={14} /> {fmt(data.summary.networkRelated)} cases</small></div><div className="complaints-metric-card"><span>Complaint Growth</span><strong className={data.summary.complaintGrowthPct >= 0 ? "risk" : "positive"}>+{data.summary.complaintGrowthPct.toFixed(1)}%</strong><small><TrendingUp size={14} /> vs previous period</small></div><div className="complaints-metric-card"><span>Critical</span><strong className="risk">{fmt(data.summary.criticalComplaints)}</strong><small><AlertCircle size={14} /> escalation required</small></div><div className="complaints-metric-card"><span>Worst-cell coverage</span><strong>{data.summary.worstCellCoverageShare.toFixed(0)}%</strong><small><MapPin size={14} /> {data.summary.worstCellsInCoverage} cells linked</small></div></section>
    <section className="complaints-filter-panel"><div className="complaints-filter-title"><Filter size={17} /><div><span className="section-kicker">COMPLAINT EXPLORER</span><h2>Find the pressure signal behind the queue</h2></div><span className="complaints-result-count">{visibleHotspots.length} hotspots match</span></div><div className="complaints-filters"><label className="complaints-search"><Search size={15} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search region or hotspot" /></label><select value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map(item => <option value={item.category} key={item.category}>{item.category}</option>)}</select><select value={severity} onChange={event => setSeverity(event.target.value as Severity)}><option value="all">All severity</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select value={region} onChange={event => setRegion(event.target.value)}><option value="all">All regions</option>{regions.map(item => <option value={item} key={item}>{item}</option>)}</select><label className={`complaints-toggle ${networkOnly ? "active" : ""}`}><input type="checkbox" checked={networkOnly} onChange={event => setNetworkOnly(event.target.checked)} /><span />Network-related only</label></div></section>
    <section className="complaints-insights-grid"><div className="complaints-category-panel"><div className="complaints-panel-head"><div><span className="section-kicker">CATEGORY MOMENTUM</span><h2>What customers are reporting</h2><p>Category momentum is shown only when period-based source records are available.</p></div><BarChart3 size={19} /></div><div className="complaints-category-list">{categories.map(item => <div className="complaints-category-row" key={item.category}><span className={`complaint-category-icon ${item.severity}`}><AlertTriangle size={14} /></span><div><b>{item.category}</b><small>{fmt(item.networkRelated)} network-related · {item.severity} severity</small></div><strong>{fmt(item.count)}<small className={item.growthPct >= 0 ? "risk" : "positive"}>{item.growthPct >= 0 ? "+" : ""}{item.growthPct.toFixed(0)}%</small></strong></div>)}</div></div><div className="complaints-trend-panel"><div className="complaints-panel-head"><div><span className="section-kicker">COMPLAINT GROWTH</span><h2>Pressure over time</h2><p>Latest operational trend from the loaded complaint source.</p></div><TrendingUp size={19} /></div><div className="complaints-trend-chart">{data.trends.length ? data.trends.map(item => <div className="complaints-trend-column" key={item.label}><div className="complaints-trend-bar" style={{ height: `${Math.max(10, item.count / maxTrend * 100)}%` }} /><span>{item.label}</span><b>{compact(item.count)}</b></div>) : <div className="complaints-empty">No period-based complaint trend records are available.</div>}</div></div><div className="complaints-severity-panel"><div className="complaints-panel-head"><div><span className="section-kicker">SEVERITY MIX</span><h2>Escalation pressure</h2></div><AlertCircle size={19} /></div><div className="complaints-severity-list">{data.severities.map(item => <div className="complaints-severity-row" key={item.severity}><span className={`severity-dot ${item.severity}`} /> <b>{item.severity}</b><i><em style={{ width: `${Math.max(5, item.count / Math.max(1, data.summary.totalComplaints) * 100)}%` }} /></i><strong>{fmt(item.count)}</strong></div>)}</div></div></section>
    <section className="complaints-main-grid"><div className="complaints-map-panel"><div className="complaints-panel-head"><div><span className="section-kicker">COMPLAINT HOTSPOTS</span><h2>Where experience is breaking down</h2><p>{networkOnly ? "Showing hotspots with network-related complaint activity." : "Hotspots are sized by complaint volume and colored by worst-cell coverage."}</p></div><span className="complaints-map-legend"><i className="complaint-map-legend-dot" /> Worst-cell coverage</span></div><div className="complaints-map-wrap"><MapView initialCenter={mapCenter} initialZoom={selected && located(selected) ? 7 : 2} className="complaints-map" onMapReady={map => { mapRef.current = map; setMapReady(true); }} onMapError={() => undefined} /><div className="complaints-coordinate-overlay"><div className="complaints-map-grid-lines" /><span className="complaints-map-label north">NORTH</span>{visibleHotspots.filter(located).map(hotspot => <button key={hotspot.id} className={`complaints-overlay-marker ${hotspot.coveredShare >= 70 ? "network" : ""} ${selected?.id === hotspot.id ? "selected" : ""}`} style={pointPosition(hotspot)} onClick={() => setSelectedId(hotspot.id)}><span>{fmt(hotspot.complaints)}</span><small>{hotspot.region}</small></button>)}</div></div></div><aside className="complaints-hotspot-panel"><div className="complaints-panel-head"><div><span className="section-kicker">HOTSPOT RANKING</span><h2>Complaint pressure by area</h2></div></div><div className="complaints-hotspot-list">{visibleHotspots.map((hotspot, index) => <button key={hotspot.id} className={`complaints-hotspot-row ${selected?.id === hotspot.id ? "selected" : ""}`} onClick={() => setSelectedId(hotspot.id)}><span className="complaints-hotspot-rank">0{index + 1}</span><span><b>{hotspot.region}</b><small>{fmt(hotspot.openComplaints)} open · {hotspot.networkShare.toFixed(0)}% network</small></span><strong>{fmt(hotspot.complaints)}<small>{hotspot.coveredShare.toFixed(0)}% worst-cell coverage</small></strong></button>)}{!visibleHotspots.length && <div className="complaints-empty"><Search size={20} /><b>No hotspots match</b><span>Adjust the complaint filters to widen the view.</span></div>}</div></aside></section>
    <section className="complaints-detail-panel">{selected ? <><div className="complaints-detail-heading"><div><span className="section-kicker">SELECTED HOTSPOT</span><h2>{selected.region}</h2><p>{selected.id} · {fmt(selected.complaints)} complaints · {selected.networkRelated ? "Network-related signal detected" : "Mixed service signal"}</p></div><span className={`complaints-correlation-pill ${selected.coveredShare >= 70 ? "critical" : "watch"}`}>{selected.coveredShare.toFixed(0)}% within worst-cell coverage</span></div><div className="complaints-detail-explanation"><div className="complaints-explanation-icon"><Network size={22} /></div><div><h3>{selected.coveredShare >= 70 ? "Network correlation confirmed" : "Network correlation requires monitoring"}</h3><p>{fmt(selected.networkRelated)} network-related complaints are concentrated around <b>{selected.worstCells.length || "the monitored"} worst cells</b>. This hotspot currently has <b>{selected.coveredShare.toFixed(0)}%</b> of network-related complaints within their coverage proxy, so radio and capacity investigation should be coordinated with CX follow-up.</p></div></div><div className="complaints-detail-metrics"><div><AlertTriangle size={16} /><span>Total</span><b>{fmt(selected.complaints)}</b></div><div><CircleDot size={16} /><span>Open</span><b>{fmt(selected.openComplaints)}</b></div><div><Network size={16} /><span>Network-related</span><b>{fmt(selected.networkRelated)}</b></div><div><AlertCircle size={16} /><span>Critical</span><b>{fmt(selected.criticalComplaints)}</b></div><div><MapPin size={16} /><span>Worst cells</span><b>{selected.worstCells.length}</b></div><div><Users size={16} /><span>Coverage share</span><b>{selected.coveredShare.toFixed(0)}%</b></div></div><div className="complaints-cell-tags"><span>Linked cells</span>{selected.worstCells.length ? selected.worstCells.map(cell => <b key={cell}>{cell}</b>) : <em>No worst cells linked</em>}</div></> : <div className="complaints-empty"><AlertTriangle size={24} /><b>Select a hotspot</b><span>Choose a region to inspect complaint/network correlation.</span></div>}</section>
  </main>;
}
