import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, Cable, CheckCircle2, ChevronRight, CircleDot, Gauge, Loader2, MapPinned, Radio, RefreshCw, Route, Server, Wifi } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Opportunity = { id: string; nodeCode: string; region: string; latitude: number; longitude: number; fiberAvailability: number; congestion: number; status: string; backhaul: "fiber" | "microwave" | "mixed" | "unknown"; plannedUpgrade: boolean | null; linkCount: number | null; opportunityScore: number; priority: "critical" | "high" | "watch" | "healthy"; recommendedAction: "Fiber Migration" | "Fiber Build" | "Microwave Expansion" | "Monitor"; rationale: string };
type Operations = { source: "persisted"; updatedAt: string; summary: { fiberNodes: number; fiberLinks: number; fiberAvailability: number; backhaulAtRisk: number; microwaveSites: number; plannedUpgrades: number; migrationOpportunities: number }; opportunities: Opportunity[]; regions: Array<{ region: string; nodes: number; availability: number; congestion: number; opportunities: number }> };

const fmt = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
const pct = (value: number) => `${value.toFixed(1)}%`;

export default function InfrastructureFiberPage() {
  const { data, isLoading, isError, refetch } = trpc.infrastructure.operations.useQuery() as { data?: Operations; isLoading: boolean; isError: boolean; refetch: () => void };
  const [selectedId, setSelectedId] = useState<string>();
  const [region, setRegion] = useState("all");
  const [onlyOpportunities, setOnlyOpportunities] = useState(false);
  const opportunities = useMemo(() => (data?.opportunities ?? []).filter(item => (region === "all" || item.region === region) && (!onlyOpportunities || item.recommendedAction !== "Monitor")), [data?.opportunities, region, onlyOpportunities]);
  const selected = opportunities.find(item => item.id === selectedId) ?? opportunities[0];
  const regions = data?.regions ?? [];

  if (isLoading) return <main className="standalone-module infrastructure-page"><div className="module-loading"><Loader2 className="animate-spin" size={22}/><span>Loading infrastructure intelligence…</span></div></main>;
  if (isError || !data) return <main className="standalone-module infrastructure-page"><div className="module-error"><AlertTriangle size={22}/><h2>Infrastructure data unavailable</h2><p>Could not load fiber and backhaul operations. Check the source connection and retry.</p><button onClick={() => refetch()}><RefreshCw size={14}/> Retry</button></div></main>;
  const s = data.summary;
  return <main className="standalone-module infrastructure-page">
    <header className="module-page-hero infrastructure-hero"><div><div className="module-kicker"><span className="live-dot"/> FIBER & FIELD OPERATIONS</div><h1>Infrastructure / Fiber</h1><p>Turn backhaul pressure into prioritized fiber migration and field actions.</p></div><div className="infrastructure-hero-icon"><Wifi size={34}/><span className="signal-ring one"/><span className="signal-ring two"/></div></header>
    <div className="infrastructure-source"><span><CircleDot size={13}/> Persisted infrastructure dataset</span><small>Updated {new Date(data.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</small><small>{s.migrationOpportunities} migration opportunities</small></div>
    <section className="infrastructure-summary-grid"><Metric icon={Server} label="Fiber nodes" value={fmt(s.fiberNodes)} hint={`${s.fiberLinks} active links`} /><Metric icon={Gauge} label="Fiber availability" value={pct(s.fiberAvailability)} hint="Regional average" tone="good" /><Metric icon={Radio} label="Backhaul at risk" value={fmt(s.backhaulAtRisk)} hint="Microwave / mixed" tone={s.backhaulAtRisk ? "risk" : "good"} /><Metric icon={Route} label="Microwave sites" value={fmt(s.microwaveSites)} hint="Capacity watch" /><Metric icon={RefreshCw} label="Planned upgrades" value={fmt(s.plannedUpgrades)} hint="Queued for delivery" tone="watch" /><Metric icon={ArrowUpRight} label="Fiber migration" value={fmt(s.migrationOpportunities)} hint="Ready targets" tone="accent" /></section>
    <section className="infrastructure-filter"><div><p className="panel-eyebrow">OPPORTUNITY EXPLORER</p><h2>Where should infrastructure act next?</h2></div><div className="infrastructure-filter-controls"><select value={region} onChange={e => setRegion(e.target.value)}><option value="all">All regions</option>{regions.map(item => <option key={item.region} value={item.region}>{item.region}</option>)}</select><label className={`infrastructure-toggle ${onlyOpportunities ? "active" : ""}`}><input type="checkbox" checked={onlyOpportunities} onChange={e => setOnlyOpportunities(e.target.checked)}/><span/> Priority actions only</label></div></section>
    <section className="infrastructure-main-grid"><div className="infrastructure-opportunity-panel"><div className="panel-heading"><div><p className="panel-eyebrow">FIBER OPPORTUNITY</p><h2>Migration queue</h2><span>Congestion × available fiber × mapped backhaul type</span></div><Cable size={20}/></div><div className="infrastructure-opportunity-list">{opportunities.map((item, index) => <button className={`infrastructure-opportunity-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelectedId(item.id)}><span className={`opportunity-rank ${item.priority}`}>{String(index + 1).padStart(2, "0")}</span><span className="opportunity-copy"><b>{item.region}</b><small>{item.nodeCode} · {item.backhaul} · {item.linkCount === null ? "links not mapped" : `${item.linkCount} links`}</small></span><span className="opportunity-bars"><i><em style={{ width: `${item.congestion}%` }}/></i><small>{item.congestion}% congestion</small></span><span className={`opportunity-action ${item.priority}`}>{item.recommendedAction}<ChevronRight size={14}/></span></button>)}{!opportunities.length && <div className="infrastructure-empty">No infrastructure opportunities match the selected filters.</div>}</div></div><div className="infrastructure-regions-panel"><div className="panel-heading"><div><p className="panel-eyebrow">REGIONAL READOUT</p><h2>Fiber footprint</h2></div><MapPinned size={20}/></div><div className="infrastructure-region-list">{regions.map(item => <button key={item.region} className={`infrastructure-region-row ${region === item.region ? "selected" : ""}`} onClick={() => setRegion(item.region)}><span className="region-marker"><span style={{ height: `${Math.max(16, item.availability)}%` }}/></span><span><b>{item.region}</b><small>{item.nodes} nodes · {item.congestion}% congestion</small></span><strong>{item.opportunities}<small>opps</small></strong></button>)}</div></div></section>
    {selected && <section className="infrastructure-detail"><div className="infrastructure-detail-heading"><div><p className="panel-eyebrow">SELECTED SITE OPPORTUNITY</p><h2>{selected.region} <span>{selected.nodeCode}</span></h2><p>{selected.rationale}</p></div><div className={`infrastructure-recommendation ${selected.priority}`}><small>RECOMMENDED ACTION</small><b>{selected.recommendedAction}</b><ArrowUpRight size={18}/></div></div><div className="infrastructure-detail-grid"><DetailMetric icon={Gauge} label="Site congestion" value={`${selected.congestion}%`} tone={selected.congestion >= 70 ? "risk" : ""}/><DetailMetric icon={Wifi} label="Fiber available" value={`${selected.fiberAvailability}%`} tone={selected.fiberAvailability >= 85 ? "good" : "risk"}/><DetailMetric icon={Radio} label="Backhaul" value={selected.backhaul}/><DetailMetric icon={Cable} label="Opportunity score" value={`${selected.opportunityScore}/100`} tone={selected.priority}/><DetailMetric icon={RefreshCw} label="Planned upgrade" value={selected.plannedUpgrade === null ? "Not mapped" : selected.plannedUpgrade ? "Yes" : "No"}/></div><div className="infrastructure-action-note"><CheckCircle2 size={16}/><span><b>Why this matters:</b> moving high-load traffic to fiber reduces microwave dependency and creates headroom for customer and enterprise growth in {selected.region}.</span></div></section>}
  </main>;
}
function Metric({ icon: Icon, label, value, hint, tone = "" }: { icon: typeof Server; label: string; value: string; hint: string; tone?: string }) { return <div className="infrastructure-metric"><span className="metric-icon"><Icon size={16}/></span><small>{label}</small><strong className={tone}>{value}</strong><em>{hint}</em></div>; }
function DetailMetric({ icon: Icon, label, value, tone = "" }: { icon: typeof Gauge; label: string; value: string; tone?: string }) { return <div className="infrastructure-detail-metric"><Icon size={15}/><span>{label}</span><b className={tone}>{value}</b></div>; }

export { InfrastructureFiberPage };
