import { useState } from "react";
import { useLocation } from "wouter";
import { ArrowRight, BrainCircuit, LockKeyhole, RadioTower, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

function SmartMark({ large = false }: { large?: boolean }) {
  return <span className={`smart-mark ${large ? "smart-mark-large" : ""}`} aria-hidden="true"><span className="smart-core" /><i className="smart-orbit orbit-one" /><i className="smart-orbit orbit-two" /><i className="smart-node node-one" /><i className="smart-node node-two" /><i className="smart-node node-three" /></span>;
}

export default function Login() {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const login = trpc.auth.localLogin.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/"); } });
  return <main className="login-shell"><section className="login-art"><div className="login-brand"><SmartMark large /><div><strong>Smart<span>Analytics</span></strong><small>AI NETWORK INTELLIGENCE</small></div></div><div className="login-orbit-scene" aria-hidden="true"><div className="orbit-glow" /><div className="orbit-line orbit-line-one" /><div className="orbit-line orbit-line-two" /><div className="scene-tower"><RadioTower size={72} strokeWidth={1.1} /><span /></div><div className="signal-node signal-node-one" /><div className="signal-node signal-node-two" /><div className="signal-node signal-node-three" /><div className="scene-label label-one">NETWORK HEALTH <b>96.7%</b></div><div className="scene-label label-two">AI SIGNALS <b>LIVE</b></div></div><div className="login-art-copy"><span className="section-kicker"><i className="live-dot" /> ZAIN JORDAN · COMMAND CENTER</span><h1>Intelligence<br /><em>in every signal.</em></h1><p>One calm, intelligent view of your telecom network, customer experience and business impact.</p><div className="login-proof"><span className="proof-icon"><BrainCircuit size={17} /></span><div><b>Smart AI operations</b><small>From network signal to next best action</small></div><span className="proof-live">LIVE</span></div></div></section><section className="login-card-wrap"><div className="login-card"><div className="login-card-head"><div className="login-card-logo"><SmartMark /><span>SMART AI / ZAIN JORDAN</span></div><span className="section-kicker">SECURE WORKSPACE ACCESS</span><h2>Welcome back</h2><p>Enter your credentials to open the telecom command center.</p></div><form onSubmit={e => { e.preventDefault(); if (username.trim() && password) login.mutate({ username, password }); }}><label><span>Username</span><div className="login-input"><UserRound size={16} /><input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} placeholder="Enter username" /></div></label><label><span>Password</span><div className="login-input"><LockKeyhole size={16} /><input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter password" /></div></label>{login.error && <div className="login-error">Unable to sign in. Check your username and password.</div>}<Button className="login-submit" type="submit" disabled={login.isPending || !username.trim() || !password}>{login.isPending ? "Opening workspace…" : <>Enter command center <ArrowRight size={16} /></>}</Button></form><div className="login-security"><ShieldCheck size={14} /><span>Protected local session · RBAC enforced</span></div></div><small className="login-footer">Smart Analytics · Telecom intelligence for Zain Jordan</small></section></main>;
}
