import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, BarChart3, CheckCircle2, CircleDollarSign, Gauge, Loader2, Megaphone, RefreshCw, ShieldAlert, Sparkles, Users, Wifi } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Campaign = { id: string; name: string; region: string; status: string; budget: number; conversionRate: number; targetArea: string; marketPotential: number; fiveGPotential: number; customerSegment: string; churnRisk: number; complaintRate: number; networkReadiness: number; fiberReadiness: number; customerExperienceRisk: boolean; riskReasons: string[]; recommendation: string };
type Operations = { source: "persisted" | "operational-preview"; updatedAt: string; summary: { campaigns: number; totalBudget: number; averageConversion: number; fiveGPotential: number; riskCampaigns: number; targetAreas: number }; campaigns: Campaign[]; segments: Array<{ segment: string; campaigns: number; budget: number; averageConversion: number }> };
const money = (value: number) => value >= 1000000 ? `$${(value / 1000000).toFixed(2)}M` : `$${Math.round(value / 1000)}K`;
const segmentLabel = (value: string) => value.replace("_", " ").replace(/\\b\\w/g, char => char.toUpperCase());

export default function MarketingPage() {
  const { data, isLoading, isError, refetch } = trpc.marketing.operations.useQuery() as { data?: Operations; isLoading: boolean; isError: boolean; refetch: () => void };
  const [segment, setSegment] = useState("all");
  const [onlyRisk, setOnlyRisk] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => (data?.campaigns ?? []).filter(item => (segment === "all" || item.customerSegment === segment) && (!onlyRisk || item.customerExperienceRisk)), [data?.campaigns, segment, onlyRisk]);
  const selected = filtered.find(item => item.id === selectedId) ?? filtered.find(item => item.customerExperienceRisk) ?? filtered[0];
  if (isLoading) return <main className="standalone-module marketing-page"><div className="module-loading"><Loader2 className="animate-spin" size={22}/><span>Loading marketing intelligence…</span></div></main>;
  if (isError || !data) return <main className="standalone-module marketing-page"><div className="module-error"><AlertTriangle size={22}/><h2>Marketing data unavailable</h2><p>Could not load campaigns and area readiness signals. Check the source connection and retry.</p><button onClick={() => refetch()}><RefreshCw size={14}/> Retry</button></div></main>;
  const summary = data.summary;
  return <main className="standalone-module marketing-page">
    <header className="module-page-hero marketing-hero"><div><div className="module-kicker"><span className="live-dot"/> CAMPAIGN PERFORMANCE</div><h1>Marketing</h1><p>Find growth pockets without sending campaigns into an avoidable customer-experience risk.</p></div><div className="marketing-hero-icon"><Sparkles size={34}/><span/></div></header>
    <div className="marketing-source"><span><BarChart3 size={13}/> {data.source === "persisted" ? "Persisted campaign dataset" : "Operational preview dataset"}</span><small>Updated {new Date(data.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</small><small>{summary.riskCampaigns} campaigns require CX review</small></div>
    <section className="marketing-summary-grid"><Metric icon={Megaphone} label="Active campaigns" value={String(summary.campaigns)} hint={`${summary.targetAreas} target areas`} /><Metric icon={CircleDollarSign} label="Campaign budget" value={money(summary.totalBudget)} hint="Allocated investment" tone="accent" /><Metric icon={Gauge} label="Avg conversion" value={`${summary.averageConversion}%`} hint="Across campaign mix" tone="good" /><Metric icon={Wifi} label="5G potential" value={`${summary.fiveGPotential}%`} hint="Addressable readiness" tone="accent" /><Metric icon={ShieldAlert} label="CX risk" value={String(summary.riskCampaigns)} hint="Review before launch" tone={summary.riskCampaigns ? "risk" : "good"} /></section>
    <section className="marketing-filter"><div><p className="panel-eyebrow">CAMPAIGN EXPLORER</p><h2>Target area readiness</h2></div><div className="marketing-filter-controls"><select value={segment} onChange={event => setSegment(event.target.value)}><option value="all">All segments</option>{data.segments.map(item => <option key={item.segment} value={item.segment}>{segmentLabel(item.segment)}</option>)}</select><label className={`marketing-toggle ${onlyRisk ? "active" : ""}`}><input type="checkbox" checked={onlyRisk} onChange={event => setOnlyRisk(event.target.checked)}/><span/> CX risk only</label></div></section>
    <section className="marketing-main-grid"><div className="marketing-campaign-panel"><div className="panel-heading"><div><p className="panel-eyebrow">CAMPAIGNS</p><h2>Campaign performance</h2><span>Reach, opportunity, readiness and risk</span></div><Megaphone size={20}/></div><div className="marketing-campaign-list">{filtered.map((item, index) => <button className={`marketing-campaign-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelectedId(item.id)}><span className={`marketing-index ${item.customerExperienceRisk ? "risk" : ""}`}>{String(index + 1).padStart(2, "0")}</span><span className="marketing-campaign-name"><b>{item.name}</b><small>{item.targetArea} · {segmentLabel(item.customerSegment)} · {item.status}</small></span><span className="marketing-budget"><b>{money(item.budget)}</b><small>{item.conversionRate}% conversion</small></span><span className="marketing-potential"><i><em style={{ width: `${item.marketPotential}%` }}/></i><small>Market {item.marketPotential}% · 5G {item.fiveGPotential}%</small></span><span className={`marketing-status ${item.customerExperienceRisk ? "risk" : "good"}`}>{item.customerExperienceRisk ? <AlertTriangle size={15}/> : <CheckCircle2 size={15}/>}</span></button>)}{!filtered.length && <div className="marketing-empty">No campaigns match the selected filters.</div>}</div></div><div className="marketing-segment-panel"><div className="panel-heading"><div><p className="panel-eyebrow">CUSTOMER SEGMENTS</p><h2>Investment mix</h2></div><Users size={20}/></div><div className="marketing-segment-list">{data.segments.map(item => <button key={item.segment} className={segment === item.segment ? "selected" : ""} onClick={() => setSegment(item.segment)}><span><b>{segmentLabel(item.segment)}</b><small>{item.campaigns} campaigns · {item.averageConversion}% conversion</small></span><strong>{money(item.budget)}</strong></button>)}</div></div></section>
    {selected && <section className={`marketing-detail ${selected.customerExperienceRisk ? "at-risk" : ""}`}><div className="marketing-detail-heading"><div><p className="panel-eyebrow">SELECTED CAMPAIGN</p><h2>{selected.name}</h2><p>{selected.targetArea} · {segmentLabel(selected.customerSegment)} · {selected.status}</p></div><div className="marketing-detail-budget"><small>CAMPAIGN BUDGET</small><b>{money(selected.budget)}</b><span>{selected.conversionRate}% conversion rate</span></div></div><div className="marketing-detail-grid"><Detail label="Target area" value={selected.region} icon={BarChart3}/><Detail label="Market potential" value={`${selected.marketPotential}%`} icon={Gauge} tone="accent"/><Detail label="5G potential" value={`${selected.fiveGPotential}%`} icon={Wifi} tone="accent"/><Detail label="Churn risk" value={`${selected.churnRisk.toFixed(1)}%`} icon={Users} tone={selected.churnRisk >= 6 ? "risk" : "good"}/><Detail label="Network readiness" value={`${Math.round(selected.networkReadiness)}%`} icon={ShieldAlert} tone={selected.networkReadiness < 70 ? "risk" : "good"}/></div><div className={`marketing-risk-callout ${selected.customerExperienceRisk ? "risk" : "good"}`}>{selected.customerExperienceRisk ? <AlertTriangle size={18}/> : <CheckCircle2 size={18}/>}<span><b>{selected.customerExperienceRisk ? "Customer Experience Risk" : "Launch readiness"}</b><small>{selected.customerExperienceRisk ? `${selected.riskReasons.join(" + ")} detected. ${selected.recommendation}` : selected.recommendation}</small></span></div></section>}
  </main>;
}
function Metric({ icon: Icon, label, value, hint, tone = "" }: { icon: typeof Megaphone; label: string; value: string; hint: string; tone?: string }) { return <div className="marketing-metric"><span><Icon size={16}/></span><small>{label}</small><strong className={tone}>{value}</strong><em>{hint}</em></div>; }
function Detail({ icon: Icon, label, value, tone = "" }: { icon: typeof Gauge; label: string; value: string; tone?: string }) { return <div className="marketing-detail-metric"><Icon size={15}/><span>{label}</span><b className={tone}>{value}</b></div>; }
export { MarketingPage };
