import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, CheckCircle2, CircleDollarSign, Gauge, Loader2, RefreshCw, Target, Users, Wifi } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Priority = { id: string; region: string; issue: string; category: string; score: number; severity: "critical" | "high" | "medium"; affectedCustomers: number; revenueRisk: number; salesPipeline: number; complaintCount: number; networkHealth: number; action: string; rationale: string; rank: number; impactScore: number };
type Operations = { source: "persisted"; updatedAt: string; summary: { count: number; critical: number; affectedCustomers: number; revenueRisk: number; highestScore: number }; priorities: Priority[] };
const money = (value: number) => value >= 1000000 ? `${(value / 1000000).toFixed(2)}M JOD` : `${Math.round(value / 1000)}K JOD`;

export default function PrioritiesPage() {
  const { data, isLoading, isError, refetch } = trpc.priorities.operations.useQuery() as { data?: Operations; isLoading: boolean; isError: boolean; refetch: () => void };
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [severity, setSeverity] = useState("all");
  const filtered = useMemo(() => (data?.priorities ?? []).filter(item => severity === "all" || item.severity === severity), [data?.priorities, severity]);
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0];
  if (isLoading) return <main className="standalone-module priorities-page"><div className="module-loading"><Loader2 className="animate-spin" size={22}/><span>Ranking today’s priorities…</span></div></main>;
  if (isError || !data) return <main className="standalone-module priorities-page"><div className="module-error"><AlertTriangle size={22}/><h2>Priority data unavailable</h2><p>Could not load the decision-support ranking. Check the source connection and retry.</p><button onClick={() => refetch()}><RefreshCw size={14}/> Retry</button></div></main>;
  const s = data.summary;
  return <main className="standalone-module priorities-page">
    <header className="module-page-hero priorities-hero"><div><div className="module-kicker"><span className="live-dot"/> DECISION SUPPORT</div><h1>Priorities</h1><p>If you can fix only five problems today, start here. Ranking combines network, customer and financial impact.</p></div><div className="priorities-hero-icon"><Target size={34}/><span/></div></header>
    <div className="priorities-source"><span><Gauge size={13}/> Persisted operational signals</span><small>Updated {new Date(data.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</small><small>{s.critical} critical signals · score {s.highestScore}/100</small></div>
    <section className="priorities-summary-grid"><Metric icon={Target} label="Actions today" value={String(s.count)} hint="Top ranked interventions"/><Metric icon={AlertTriangle} label="Critical signals" value={String(s.critical)} hint="Immediate attention" tone="risk"/><Metric icon={Users} label="Customers affected" value={s.affectedCustomers.toLocaleString()} hint="Across top five" tone="accent"/><Metric icon={CircleDollarSign} label="Revenue risk" value={money(s.revenueRisk)} hint="Monthly exposure" tone="risk"/></section>
    <section className="priorities-filter"><div><p className="panel-eyebrow">TODAY'S DECISION QUEUE</p><h2>Top 5 Priorities Today</h2><span>Ranked by combined customer and revenue impact</span></div><select value={severity} onChange={event => setSeverity(event.target.value)}><option value="all">All severities</option><option value="critical">Critical only</option><option value="high">High only</option><option value="medium">Medium only</option></select></section>
    <section className="priorities-layout"><div className="priority-list">{filtered.map(item => <button key={item.id} className={`priority-row ${selected?.id === item.id ? "selected" : ""}`} onClick={() => setSelectedId(item.id)}><span className={`priority-rank ${item.severity}`}>{item.rank}</span><span className="priority-main"><b>{item.region}</b><strong>{item.issue}</strong><small>{item.rationale}</small></span><span className="priority-impact"><b>{item.impactScore}</b><small>impact score</small></span><span className="priority-financial"><b>{money(item.revenueRisk)}</b><small>revenue risk</small></span><span className={`priority-severity ${item.severity}`}>{item.severity}</span><ArrowUpRight size={16}/></button>)}{!filtered.length && <div className="priority-empty">No priorities match the selected severity.</div>}</div><aside className="priority-side"><div className="panel-heading"><div><p className="panel-eyebrow">ACTION MIX</p><h2>What to do next</h2></div><Target size={20}/></div>{Array.from(new Set(filtered.map(item => item.action))).slice(0, 4).map(action => <div className="action-mix" key={action}><span>{action}</span><b>{filtered.filter(item => item.action === action).length}</b></div>)}<div className="priority-lens"><Wifi size={16}/><span><b>Decision lens</b><small>Fix the issues that protect the most customers and monthly revenue first.</small></span></div></aside></section>
    {selected && <section className={`priority-detail ${selected.severity}`}><div className="priority-detail-heading"><div><p className="panel-eyebrow">PRIORITY #{selected.rank}</p><h2>{selected.region} · {selected.issue}</h2><p>{selected.severity.toUpperCase()} · {selected.category} signal · Impact score {selected.impactScore}/100</p></div><div className="priority-action"><small>RECOMMENDED ACTION</small><b>{selected.action}</b></div></div><div className="priority-detail-grid"><Detail icon={Users} label="Customers affected" value={selected.affectedCustomers.toLocaleString()} tone="accent"/><Detail icon={CircleDollarSign} label="Revenue risk" value={money(selected.revenueRisk)} tone="risk"/><Detail icon={AlertTriangle} label="Open complaints" value={selected.complaintCount.toLocaleString()}/><Detail icon={Wifi} label="Network health" value={`${Math.round(selected.networkHealth)}%`} tone={selected.networkHealth < 50 ? "risk" : "good"}/><Detail icon={Target} label="Sales pipeline" value={money(selected.salesPipeline)} tone="good"/></div><div className={`priority-callout ${selected.severity}`}><AlertTriangle size={18}/><span><b>Why this is ranked #{selected.rank}</b><small>{selected.rationale} Resolve with {selected.action.toLowerCase()} to reduce exposure before moving to the next item.</small></span></div></section>}
  </main>;
}
function Metric({ icon: Icon, label, value, hint, tone = "" }: { icon: typeof Target; label: string; value: string; hint: string; tone?: string }) { return <div className="priority-metric"><span><Icon size={16}/></span><small>{label}</small><strong className={tone}>{value}</strong><em>{hint}</em></div>; }
function Detail({ icon: Icon, label, value, tone = "" }: { icon: typeof Target; label: string; value: string; tone?: string }) { return <div className="priority-detail-metric"><Icon size={15}/><span>{label}</span><b className={tone}>{value}</b></div>; }
export { PrioritiesPage };
