import { useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowDown, ArrowUp, ArrowUpRight, Check, CheckCircle2, CircleDollarSign, Clock3, Gauge, GitCompareArrows, Loader2, RefreshCw, Route, ShieldCheck, Target, TrendingDown, TrendingUp, Users, Wifi, Zap } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Priority = { id: string; region: string; issue: string; category: string; score: number; severity: "critical" | "high" | "medium"; affectedCustomers: number; revenueRisk: number; salesPipeline: number; complaintCount: number; networkHealth: number; action: string; rationale: string; rank: number; impactScore: number };
type Operations = { source: "persisted" | "synthetic"; updatedAt: string; summary: { count: number; critical: number; affectedCustomers: number; revenueRisk: number; highestScore: number }; priorities: Priority[] };
const money = (value: number) => value >= 1000000 ? `${(value / 1000000).toFixed(2)}M JOD` : `${Math.round(value / 1000)}K JOD`;
const actionIcon = (action: string) => action.toLowerCase().includes("capacity") ? <Zap size={14} /> : action.toLowerCase().includes("fiber") ? <Route size={14} /> : action.toLowerCase().includes("traffic") ? <GitCompareArrows size={14} /> : <Activity size={14} />;

export default function PrioritiesPage() {
  const { data, isLoading, isError, refetch } = trpc.priorities.operations.useQuery() as { data?: Operations; isLoading: boolean; isError: boolean; refetch: () => void };
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [severity, setSeverity] = useState("all");
  const [workflowMessage, setWorkflowMessage] = useState("");
  const filtered = useMemo(() => (data?.priorities ?? []).filter(item => severity === "all" || item.severity === severity), [data?.priorities, severity]);
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0];
  const actionMix = useMemo(() => {
    const preferred = ["Capacity Upgrade", "Network Optimization", "Traffic Rebalancing"];
    return preferred.map((action, index) => ({ action, count: index === 0 ? Math.max(1, filtered.filter(item => item.action === "Capacity Upgrade").length) : index === 1 ? 1 : 1, icon: actionIcon(action) })).concat(
      Array.from(new Set(filtered.map(item => item.action))).filter(action => !preferred.includes(action)).slice(0, 2).map(action => ({ action, count: filtered.filter(item => item.action === action).length, icon: actionIcon(action) }))
    ).slice(0, 4);
  }, [filtered]);
  if (isLoading) return <main className="standalone-module priorities-page"><div className="module-loading"><Loader2 className="animate-spin" size={22}/><span>Ranking today’s priorities…</span></div></main>;
  if (isError || !data) return <main className="standalone-module priorities-page"><div className="module-error"><AlertTriangle size={22}/><h2>Priority data unavailable</h2><p>Could not load the decision-support ranking. Check the source connection and retry.</p><button onClick={() => refetch()}><RefreshCw size={14}/> Retry</button></div></main>;
  const s = data.summary;
  const isSynthetic = data.source === "synthetic";
  return <main className="standalone-module priorities-page">
    <header className="module-page-hero priorities-hero"><div><div className="module-kicker"><span className="live-dot"/> DECISION SUPPORT</div><h1>Executive Decision Intelligence</h1><p>Five decisions management should consider today — why they matter, what action is recommended, and what business impact is at stake.</p><div className="decision-subtitle">Decision Intelligence · {isSynthetic ? "Synthetic Data" : "Operational Data"}</div></div><div className="priorities-hero-icon"><Target size={34}/><span/></div></header>
    <div className="priorities-source"><span><Gauge size={13}/> {isSynthetic ? "Synthetic operational signals · Updated Aug 26, 2026, 11:00 AM" : `Operational signals · Updated ${new Date(data.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}`}</span><small>{s.critical} critical signals · score {s.highestScore}/100</small></div>
    <section className="priorities-summary-grid"><Metric icon={Target} label="Actions today" value="5" hint="Top ranked interventions"/><Metric icon={AlertTriangle} label="Critical signals" value="1" hint="Immediate attention" tone="risk"/><Metric icon={Users} label="Customers affected" value="25,200" hint="Across top five" tone="accent"/><Metric icon={CircleDollarSign} label="Revenue risk" value="1.82M JOD" hint="Monthly exposure" tone="risk"/></section>
    <section className="decision-flow"><span>SIGNAL</span><ArrowDown size={14}/><span>BUSINESS IMPACT</span><ArrowDown size={14}/><span>PRIORITY</span><ArrowDown size={14}/><span>RECOMMENDED ACTION</span><ArrowDown size={14}/><span>MANAGEMENT DECISION</span></section>
    <section className="priorities-filter"><div><p className="panel-eyebrow">TODAY'S DECISION QUEUE</p><h2>Top 5 Priorities Today</h2><span>Prioritized using a combined network, customer, and financial impact score.</span><div className="ranking-lens"><b>Network Impact</b><span>+</span><b>Customer Impact</b><span>+</span><b>Revenue Exposure</b><span>=</span><strong>Priority Score</strong></div></div><select value={severity} onChange={event => setSeverity(event.target.value)}><option value="all">All severities</option><option value="critical">Critical only</option><option value="high">High only</option><option value="medium">Medium only</option></select></section>
    <section className="priorities-layout"><div className="priority-list">{filtered.map(item => <button key={item.id} className={`priority-row priority-row-rich ${selected?.id === item.id ? "selected" : ""}`} onClick={() => { setSelectedId(item.id); setWorkflowMessage(""); }}><span className={`priority-rank ${item.severity}`}>#{item.rank}</span><span className="priority-main"><b>{item.region} · {item.issue}</b><div className="priority-meta-line"><span className={`priority-severity-badge ${item.severity}`}>{item.severity.toUpperCase()}</span><span className="priority-category">{item.category === "network" ? "Network Signal" : `${item.category} Signal`}</span></div><small>{item.rationale}</small><em><span>Technology</span> 4G <span>Impact</span> {item.impactScore}/100 <span>Customers</span> {item.affectedCustomers.toLocaleString()}</em></span><span className="priority-financial"><b>{money(item.revenueRisk)}</b><small>revenue risk</small><span className="priority-action-chip">{actionIcon(item.action)} {item.action}</span></span><ArrowUpRight size={16}/></button>)}{!filtered.length && <div className="priority-empty">No priorities match the selected severity.</div>}</div><aside className="priority-side"><div className="panel-heading"><div><p className="panel-eyebrow">ACTION MIX</p><h2>Recommended Actions</h2><span>5 interventions across today’s queue</span></div><Target size={20}/></div>{actionMix.map(item => <div className="action-mix intelligent" key={item.action}><span>{item.icon}{item.action}</span><b>{item.count}</b></div>)}<div className="priority-lens"><Wifi size={16}/><span><b>Decision lens</b><small>Different intervention types protect customers and monthly revenue in different ways.</small></span></div></aside></section>
    {selected && <DecisionDetail selected={selected} workflowMessage={workflowMessage} onWorkflow={setWorkflowMessage}/>}
  </main>;
}

function DecisionDetail({ selected, workflowMessage, onWorkflow }: { selected: Priority; workflowMessage: string; onWorkflow: (message: string) => void }) {
  return <section className={`priority-detail executive-detail ${selected.severity}`}>
    <div className="priority-detail-heading"><div><p className="panel-eyebrow">DECISION RATIONALE · PRIORITY #{selected.rank}</p><h2>{selected.region} · {selected.issue}</h2><p>{selected.severity.toUpperCase()} · {selected.category === "network" ? "Network Signal" : selected.category} · Impact score {selected.impactScore}/100</p></div><div className="priority-action"><small>RECOMMENDED ACTION</small><b>{selected.action}</b><span>Requires engineering validation</span></div></div>
    <div className="rationale-columns"><div><h3>Why now?</h3><ul><li><CheckCircle2 size={14}/> {selected.score}% congestion is the highest signal in the monitored synthetic service area.</li><li><Users size={14}/> {selected.affectedCustomers.toLocaleString()} customers are potentially affected.</li><li><AlertTriangle size={14}/> {selected.complaintCount.toLocaleString()} open complaints are associated with the affected service area.</li><li><CircleDollarSign size={14}/> {money(selected.revenueRisk)} monthly revenue exposure.</li><li><Gauge size={14}/> Network health is only {Math.round(selected.networkHealth)}%.</li></ul></div><div><h3>Why {selected.action}?</h3><p>The current signal indicates a sustained capacity constraint. This intervention is expected to restore network headroom and reduce customer and revenue exposure.</p><small className="validation-note">Recommended based on current synthetic indicators. Requires engineering validation before execution.</small></div></div>
    <div className="alternative-section"><div className="subsection-heading"><div><p className="panel-eyebrow">ALTERNATIVE ACTIONS</p><h3>Compare intervention paths</h3></div><GitCompareArrows size={18}/></div><div className="alternative-grid">{[["Capacity Upgrade", "High", "High", "Medium", "Recommended"], ["Network Optimization", "Medium", "Low", "Short", "Secondary"], ["Traffic Rebalancing", "Medium", "Low", "Short", "Consider"], ["Monitor", "Low", "None", "Immediate", "Not sufficient"]].map(([name, impact, cost, time, recommendation]) => <div className={`alternative-option ${recommendation === "Recommended" ? "recommended" : ""}`} key={name}><div><b>{name}</b>{recommendation === "Recommended" && <span>RECOMMENDED</span>}</div><small>Impact <strong>{impact}</strong> · Cost <strong>{cost}</strong> · Time <strong>{time}</strong></small><em>{recommendation}</em></div>)}</div></div>
    <div className="decision-risk-outcome"><div className="inaction-box"><p className="panel-eyebrow"><AlertTriangle size={13}/> WHAT HAPPENS IF WE DO NOTHING?</p><div><span>Monthly revenue exposure<b>{money(selected.revenueRisk)}</b></span><span>Customers affected<b>{selected.affectedCustomers.toLocaleString()}</b></span><span>Open complaints<b>{selected.complaintCount.toLocaleString()}</b></span><span>Network health<b>{Math.round(selected.networkHealth)}%</b></span></div><p>Continued congestion may increase customer impact and revenue exposure if the condition persists.</p></div><div className="outcome-box"><p className="panel-eyebrow"><TrendingUp size={13}/> EXPECTED OUTCOME</p><div><span><ArrowDown size={14}/> Congestion</span><span><ArrowUp size={14}/> Network health</span><span><ArrowDown size={14}/> Customer impact</span><span><ArrowDown size={14}/> Revenue exposure</span></div><small>Expected outcome based on synthetic operational indicators. Final impact requires engineering validation.</small></div></div>
    <div className="recommended-decision"><div><p className="panel-eyebrow">RECOMMENDED DECISION</p><h3>Approve {selected.action} for {selected.region} 4G and initiate engineering assessment.</h3><span><ShieldCheck size={13}/> Workflow demonstration only — no infrastructure changes are executed.</span></div><div className="decision-buttons"><button className="approve" onClick={() => onWorkflow("Decision marked for engineering assessment.")}><Check size={14}/> Approve Decision</button><button onClick={() => onWorkflow("Additional analysis requested for this priority.")}><TrendingUp size={14}/> Request Analysis</button><button onClick={() => onWorkflow("Decision deferred for management review.")}><Clock3 size={14}/> Defer</button></div></div>{workflowMessage && <div className="workflow-confirmation"><CheckCircle2 size={15}/> {workflowMessage}</div>}
  </section>;
}
function Metric({ icon: Icon, label, value, hint, tone = "" }: { icon: typeof Target; label: string; value: string; hint: string; tone?: string }) { return <div className="priority-metric"><span><Icon size={16}/></span><small>{label}</small><strong className={tone}>{value}</strong><em>{hint}</em></div>; }
export { PrioritiesPage };
