import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, BriefcaseBusiness, Building2, CheckCircle2, ChevronRight, CircleDollarSign, Gauge, Loader2, MapPinned, RefreshCw, Route, ShieldAlert, Wifi } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Opportunity = { id: string; accountName: string; region: string; latitude: number; longitude: number; stage: string; value: number; probability: number; enterprise: boolean; customerSegment: string; networkReadiness: number; fiberReadiness: number; siteName: string; weightedValue: number; networkIssue: boolean; alert: string | null };
type Operations = { source: "persisted"; updatedAt: string; summary: { opportunities: number; pipelineValue: number; weightedPipeline: number; enterpriseOpportunities: number; networkAtRisk: number; fiberReady: number }; stages: Array<{ stage: string; count: number; value: number; share: number }>; opportunities: Opportunity[] };
const money = (value: number) => value >= 1000000 ? `$${(value / 1000000).toFixed(2)}M` : `$${Math.round(value / 1000)}K`;
const readiness = (value: number) => `${Math.round(value)}%`;

export default function SalesPage() {
  const { data, isLoading, isError, refetch } = trpc.sales.operations.useQuery() as { data?: Operations; isLoading: boolean; isError: boolean; refetch: () => void };
  const [stage, setStage] = useState("all");
  const [onlyRisk, setOnlyRisk] = useState(false);
  const filtered = useMemo(() => (data?.opportunities ?? []).filter(item => (stage === "all" || item.stage === stage) && (!onlyRisk || item.networkIssue)), [data?.opportunities, stage, onlyRisk]);
  const selected = filtered[0];
  if (isLoading) return <main className="standalone-module sales-page"><div className="module-loading"><Loader2 className="animate-spin" size={22}/><span>Loading sales intelligence…</span></div></main>;
  if (isError || !data) return <main className="standalone-module sales-page"><div className="module-error"><AlertTriangle size={22}/><h2>Sales data unavailable</h2><p>Could not load pipeline and readiness intelligence. Check the source connection and retry.</p><button onClick={() => refetch()}><RefreshCw size={14}/> Retry</button></div></main>;
  const s = data.summary;
  return <main className="standalone-module sales-page">
    <header className="module-page-hero sales-hero"><div><div className="module-kicker"><span className="live-dot"/> SALES INTELLIGENCE</div><h1>Sales</h1><p>Protect pipeline value by making network readiness part of every commercial decision.</p></div><div className="sales-hero-icon"><BriefcaseBusiness size={34}/><span className="sales-pulse"/></div></header>
    <div className="sales-source"><span><CircleDollarSign size={13}/> Persisted sales dataset</span><small>Updated {new Date(data.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</small><small>{s.networkAtRisk} opportunities need network review</small></div>
    <section className="sales-summary-grid"><Metric icon={BriefcaseBusiness} label="Sales opportunities" value={String(s.opportunities)} hint={`${s.enterpriseOpportunities} enterprise`} /><Metric icon={CircleDollarSign} label="Qualified pipeline" value={money(s.pipelineValue)} hint={`${money(s.weightedPipeline)} weighted`} tone="accent" /><Metric icon={Building2} label="Enterprise opportunities" value={String(s.enterpriseOpportunities)} hint="Strategic accounts" tone="good" /><Metric icon={ShieldAlert} label="Network at risk" value={String(s.networkAtRisk)} hint="Readiness review" tone={s.networkAtRisk ? "risk" : "good"} /><Metric icon={Wifi} label="Fiber ready" value={String(s.fiberReady)} hint="Commercially enabled" tone="good" /></section>
    <section className="sales-filter"><div><p className="panel-eyebrow">PIPELINE EXPLORER</p><h2>Commercial readiness queue</h2></div><div className="sales-filter-controls"><select value={stage} onChange={e => setStage(e.target.value)}><option value="all">All stages</option>{data.stages.map(item => <option key={item.stage} value={item.stage}>{item.stage}</option>)}</select><label className={`sales-toggle ${onlyRisk ? "active" : ""}`}><input type="checkbox" checked={onlyRisk} onChange={e => setOnlyRisk(e.target.checked)}/><span/> Network risk only</label></div></section>
    <section className="sales-main-grid"><div className="sales-opportunity-panel"><div className="panel-heading"><div><p className="panel-eyebrow">OPPORTUNITIES</p><h2>Pipeline watchlist</h2><span>Location, stage, readiness and value</span></div><MapPinned size={20}/></div><div className="sales-opportunity-list">{filtered.map((item, index) => <button className={`sales-opportunity-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id}><span className={`sales-index ${item.networkIssue ? "risk" : ""}`}>{String(index + 1).padStart(2, "0")}</span><span className="sales-account"><b>{item.accountName}</b><small>{item.region} · {item.stage} · {item.enterprise ? "Enterprise" : item.customerSegment === "unknown" ? "Segment not mapped" : "High value"}</small></span><span className="sales-value"><b>{money(item.value)}</b><small>{item.probability}% probability</small></span><span className="sales-readiness"><i><em style={{ width: `${item.networkReadiness}%` }}/></i><small>Network {readiness(item.networkReadiness)} · Fiber {readiness(item.fiberReadiness)}</small></span><span className={`sales-alert-mark ${item.networkIssue ? "risk" : "good"}`}>{item.networkIssue ? <AlertTriangle size={15}/> : <CheckCircle2 size={15}/>}<ChevronRight size={13}/></span></button>)}{!filtered.length && <div className="sales-empty">No opportunities match the selected filters.</div>}</div></div><div className="sales-stage-panel"><div className="panel-heading"><div><p className="panel-eyebrow">PIPELINE MIX</p><h2>Opportunity stages</h2></div><Route size={20}/></div><div className="sales-stage-list">{data.stages.map(item => <button key={item.stage} className={stage === item.stage ? "selected" : ""} onClick={() => setStage(item.stage)}><span className="sales-stage-bar"><i style={{ width: `${Math.max(8, item.share)}%` }}/></span><span><b>{item.stage}</b><small>{item.count} opportunities · {item.share}% of value</small></span><strong>{money(item.value)}</strong></button>)}</div></div></section>
    {selected && <section className={`sales-detail ${selected.networkIssue ? "at-risk" : ""}`}><div className="sales-detail-heading"><div><p className="panel-eyebrow">SELECTED OPPORTUNITY</p><h2>{selected.accountName}</h2><p>{selected.siteName} · {selected.region} · {selected.stage}</p></div><div className="sales-detail-value"><small>OPPORTUNITY VALUE</small><b>{money(selected.value)}</b><span>{selected.probability}% close probability</span></div></div><div className="sales-detail-grid"><Detail label="Customer location" value={selected.region} icon={MapPinned}/><Detail label="Network readiness" value={readiness(selected.networkReadiness)} icon={Gauge} tone={selected.networkIssue ? "risk" : "good"}/><Detail label="Fiber readiness" value={readiness(selected.fiberReadiness)} icon={Wifi} tone={selected.fiberReadiness >= 85 ? "good" : "risk"}/><Detail label="Opportunity stage" value={selected.stage} icon={Route}/><Detail label="Weighted value" value={money(selected.weightedValue)} icon={CircleDollarSign} tone="accent"/></div>{selected.alert ? <div className="sales-alert"><AlertTriangle size={17}/><span><b>Sales alert:</b> {selected.alert} Review site capacity and customer experience before committing the commercial timeline.</span></div> : <div className="sales-alert good"><CheckCircle2 size={17}/><span><b>Commercial readiness:</b> Network and fiber signals currently support progressing this opportunity.</span></div>}</section>}
  </main>;
}
function Metric({ icon: Icon, label, value, hint, tone = "" }: { icon: typeof BriefcaseBusiness; label: string; value: string; hint: string; tone?: string }) { return <div className="sales-metric"><span><Icon size={16}/></span><small>{label}</small><strong className={tone}>{value}</strong><em>{hint}</em></div>; }
function Detail({ icon: Icon, label, value, tone = "" }: { icon: typeof Gauge; label: string; value: string; tone?: string }) { return <div className="sales-detail-metric"><Icon size={15}/><span>{label}</span><b className={tone}>{value}</b></div>; }
export { SalesPage };
